### ISSUE TITLE
Rename files; directory cleanups

### ISSUE THREAD

**Issue by hershal** [hershic/cs231n#19]
These files are named incredibly stupidly and take way too long to type out. The class names should be the only long-ish names, so that they are distinguished clearly in code. The filenames, however, need not be so long. 

E.g. this
```
classifiers
├── __init__.py
├── __pycache__
├── classifier_softmax.py
├── k_nearest_neighbor.py
├── linear_classifier.py
├── linear_svm.py
├── neural_net.py
└── test
    ├── __pycache__
    ├── test_classifier_softmax.py
    ├── test_k_nearest_neighbor.py
    └── test_linear_svm.py
```

could be simplified to 
```
classifiers
├── __init__.py
├── __pycache__
├── softmax.py
├── knn.py
├── svm.py
└── test
    ├── __pycache__
    ├── softmax.py
    ├── knn.py
    └── svm.py
```

**Comment by hershal** [comment]
Also we should remove all dangling files which are not used anywhere.

**Comment by EricCrosson** [comment]
Do you have a classy way to detect these dangers?

**Comment by EricCrosson** [comment]
Weird, this didn't close from your comment, even though it looks like it [would have](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in a commit :confused:

**Comment by hershal** [comment]
Good question. Maybe a static analysis tool would do this? `pyreverse` comes to mind because it generates a graph of python modules, but I'm not sure this would work properly since our entry point is currently through the tests...
