### ISSUE TITLE
Implement Bias in LayerFullyConnected

### ISSUE THREAD

**Issue by hershal** [hershic/cs231n#2]

**Comment by hershal** [comment]
Looks like most people append bias to the weights. I don't know how that will influence the regularization or Layer API. The main ask is to make a clean API where the network learns the optimal weights *and* biases.

**Comment by hershal** [comment]
I could have `self.weights` and `self.bias`. I don't know how that will influence backprop or classification. Looks like most people just deal with another column in their weight matrix and only treat it specially in the layer calculations. This seems ok. I'll have to do some experiments after the network is actually working.

**Comment by EricCrosson** [comment]
I have seen this too, it seems sound
