### ISSUE TITLE
Come up with a better dataset naming scheme

### ISSUE THREAD

**Issue by hershal** [hershic/cs231n#7]
I'm using Points and Labels to describe a data set, but those are still ambiguous. Ideally we should have something like:

Dataset (e.g. CIFAR-10) -> Batch (e.g. a fold) -> Datamap (e.g. array of pixels and an associated classification of those pixels)

**Comment by EricCrosson** [comment]
How does an array of pixels and associated classifications give us any different information from 'points and labels'?

**Comment by hershal** [comment]
The problem is when I refer to "points" in most places I really mean a batch of points, i.e. 5000x3072. I suppose I could rectify this ambiguity by renaming the variable to `batch_points` (or equivalent).

**Comment by hershal** [comment]
See PR #13
